-- RecFindOBM — Seed Oakville Facilities (17 facilities)
-- Run after 001_initial_schema.sql

INSERT INTO facilities (id, name, facility_type, address, location, phone, website_url, amenities, has_pool, has_arena, has_fitness, notes) VALUES ('glen_abbey_cc', 'Glen Abbey Community Centre', 'community_center', '1415 Third Line, Oakville, ON L6M 3G2', ST_SetSRID(ST_MakePoint(-79.7178, 43.4308), 4326), '905-815-5950', 'https://www.oakville.ca/parks-recreation-culture/facilities-rentals/facility-locations/community-centres/', ARRAY['pool','arena_twin_pad','fitness_centre','squash_courts','library','community_rooms'], TRUE, TRUE, TRUE, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facilities (id, name, facility_type, address, location, phone, website_url, amenities, has_pool, has_arena, has_fitness, notes) VALUES ('iroquois_ridge_cc', 'Iroquois Ridge Community Centre', 'community_center', '1051 Glenashton Drive, Oakville, ON L6H 5L1', ST_SetSRID(ST_MakePoint(-79.6877, 43.4485), 4326), '905-338-4255', 'https://www.oakville.ca/parks-recreation-culture/facilities-rentals/facility-locations/community-centres/', ARRAY['pool','fitness_centre','library','older_adults_centre','community_rooms'], TRUE, FALSE, TRUE, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facilities (id, name, facility_type, address, location, phone, website_url, amenities, has_pool, has_arena, has_fitness, notes) VALUES ('oakville_trafalgar_cc', 'Oakville Trafalgar Community Centre', 'community_center', '325 Reynolds Street, Oakville, ON L6J 3L2', ST_SetSRID(ST_MakePoint(-79.6682, 43.4435), 4326), '905-815-6050', 'https://www.oakville.ca/parks-recreation-culture/facilities-rentals/facility-locations/community-centres/', ARRAY['pool_lap','pool_leisure','fitness_centre','community_rooms'], TRUE, FALSE, TRUE, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facilities (id, name, facility_type, address, location, phone, website_url, amenities, has_pool, has_arena, has_fitness, notes) VALUES ('qepccc', 'Queen Elizabeth Park Community & Cultural Centre', 'community_center', '2302 Bridge Road, Oakville, ON L6L 2G6', ST_SetSRID(ST_MakePoint(-79.6395, 43.4148), 4326), '905-815-5979', 'https://www.oakville.ca/parks-recreation-culture/facilities-rentals/facility-locations/community-centres/', ARRAY['pool','fitness_centre','gym_double','gym_single','youth_centre','seniors_centre','library','woodworking_shop','art_studios'], TRUE, FALSE, TRUE, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facilities (id, name, facility_type, address, location, phone, website_url, amenities, has_pool, has_arena, has_fitness, notes) VALUES ('river_oaks_cc', 'River Oaks Community Centre', 'community_center', '2400 Sixth Line, Oakville, ON L6H 6W3', ST_SetSRID(ST_MakePoint(-79.7425, 43.434), 4326), '905-257-6800', 'https://www.oakville.ca/parks-recreation-culture/facilities-rentals/facility-locations/community-centres/', ARRAY['arena_twin_pad','fitness_centre','indoor_track','community_rooms','older_adults_centre','massage_therapy'], FALSE, TRUE, TRUE, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facilities (id, name, facility_type, address, location, phone, website_url, amenities, has_pool, has_arena, has_fitness, notes) VALUES ('trafalgar_park_cc', 'Trafalgar Park Community Centre', 'community_center', '133 Rebecca Street, Oakville, ON L6K 1J2', ST_SetSRID(ST_MakePoint(-79.671, 43.4468), 4326), '905-845-6601', 'https://www.oakville.ca/parks-recreation-culture/facilities-rentals/facility-locations/community-centres/', ARRAY['arena','community_rooms','outdoor_rink_seasonal'], FALSE, TRUE, FALSE, 'Renovations started Jan 2025 \u2014 verify current status') ON CONFLICT (id) DO NOTHING;
INSERT INTO facilities (id, name, facility_type, address, location, phone, website_url, amenities, has_pool, has_arena, has_fitness, notes) VALUES ('sixteen_mile_sc', 'Sixteen Mile Sports Complex', 'arena', '3070 Neyagawa Boulevard, Oakville, ON L6M 4S1', ST_SetSRID(ST_MakePoint(-79.734, 43.4545), 4326), '905-815-5970', 'https://www.oakville.ca/parks-recreation-culture/facilities-rentals/facility-locations/community-centres/', ARRAY['arena_quad_pad','olympic_ice_pad','community_rooms'], FALSE, TRUE, FALSE, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facilities (id, name, facility_type, address, location, phone, website_url, amenities, has_pool, has_arena, has_fitness, notes) VALUES ('joshuas_creek_arenas', 'Joshua''s Creek Arenas', 'arena', '1663 North Service Road East, Oakville, ON L6H 7T1', ST_SetSRID(ST_MakePoint(-79.6628, 43.4592), 4326), '905-815-5990', 'https://www.oakville.ca/parks-recreation-culture/facilities-rentals/facility-locations/arenas/', ARRAY['arena_twin_pad','shooter_pads'], FALSE, TRUE, FALSE, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facilities (id, name, facility_type, address, location, phone, website_url, amenities, has_pool, has_arena, has_fitness, notes) VALUES ('maple_grove_arena', 'Maple Grove Arena', 'arena', '2237 Devon Road, Oakville, ON L6J 5M1', ST_SetSRID(ST_MakePoint(-79.6535, 43.4195), 4326), '905-815-5985', 'https://www.oakville.ca/parks-recreation-culture/facilities-rentals/facility-locations/arenas/', ARRAY['arena'], FALSE, TRUE, FALSE, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facilities (id, name, facility_type, address, location, phone, website_url, amenities, has_pool, has_arena, has_fitness, notes) VALUES ('kinoak_arena', 'Kinoak Arena', 'arena', '363 Warminster Drive, Oakville, ON L6L 4N1', ST_SetSRID(ST_MakePoint(-79.6382, 43.408), 4326), '905-815-5982', 'https://www.oakville.ca/parks-recreation-culture/facilities-rentals/facility-locations/arenas/', ARRAY['arena'], FALSE, TRUE, FALSE, 'Currently closed \u2014 verify status before launch') ON CONFLICT (id) DO NOTHING;
INSERT INTO facilities (id, name, facility_type, address, location, phone, website_url, amenities, has_pool, has_arena, has_fitness, notes) VALUES ('oakville_central_library', 'Oakville Public Library - Central Branch', 'library', '120 Navy Street, Oakville, ON L6J 2Z4', ST_SetSRID(ST_MakePoint(-79.669, 43.446), 4326), '905-815-2042', 'https://www.opl.ca/hours-locations', ARRAY['library','meeting_rooms','makerspace'], FALSE, FALSE, FALSE, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facilities (id, name, facility_type, address, location, phone, website_url, amenities, has_pool, has_arena, has_fitness, notes) VALUES ('white_oaks_library', 'Oakville Public Library - White Oaks Branch', 'library', '1515 Rebecca Street, Oakville, ON L6L 2B5', ST_SetSRID(ST_MakePoint(-79.6218, 43.409), 4326), '905-815-2042', 'https://www.opl.ca/hours-locations', ARRAY['library'], FALSE, FALSE, FALSE, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facilities (id, name, facility_type, address, location, phone, website_url, amenities, has_pool, has_arena, has_fitness, notes) VALUES ('sir_john_colborne', 'Sir John Colborne Recreation Centre for Seniors', 'seniors_centre', '1565 Old Lakeshore Road, Oakville, ON L6L 1A3', ST_SetSRID(ST_MakePoint(-79.621, 43.4055), 4326), '905-815-5960', 'https://www.oakville.ca/parks-recreation-culture/facilities-rentals/facility-locations/seniors-centres/', ARRAY['seniors_programs','auditorium','art_rooms','lounge'], FALSE, FALSE, FALSE, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facilities (id, name, facility_type, address, location, phone, website_url, amenities, has_pool, has_arena, has_fitness, notes) VALUES ('white_oaks_pool', 'White Oaks Pool', 'pool', '1515 White Oaks Boulevard, Oakville, ON L6H 3E1', ST_SetSRID(ST_MakePoint(-79.654, 43.411), 4326), '905-815-5975', 'https://www.oakville.ca/parks-recreation-culture/facilities-rentals/facility-locations/', ARRAY['pool'], TRUE, FALSE, FALSE, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facilities (id, name, facility_type, address, location, phone, website_url, amenities, has_pool, has_arena, has_fitness, notes) VALUES ('oakville_museum', 'Oakville Museum', 'museum', '8 Navy Street, Oakville, ON L6J 2Y5', ST_SetSRID(ST_MakePoint(-79.6672, 43.4428), 4326), '905-338-4400', 'https://www.oakville.ca/parks-recreation-culture/arts-culture/oakville-museum/', ARRAY['museum','exhibitions','guided_tours'], FALSE, FALSE, FALSE, NULL) ON CONFLICT (id) DO NOTHING;
